/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package subset_sum_problem;

public class App {

    public static void main(String[] args) throws Exception
    {
        System.out.println("\n>> iTunesEntrySubsetSumProblem();");
        AlgorithmForiTunesEntry.iTunesEntrySubsetSumProblem();
        
        System.out.println("\n>> integerSubsetSumProblem();");
        AlgorithmForInteger.integerSubsetSumProblem();
        
    }
}
